// <auto-generated />
using System;
using Fotografia.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fotografia.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260531164304_AddRolesProfileCommentsFavorites")]
    partial class AddRolesProfileCommentsFavorites
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fotografia.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualizadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documento")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasFilter("[UsuarioId] IS NOT NULL");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.ComentarioEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ComentariosEventos", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.ComentarioFoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FotoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ComentariosFotos", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Descarga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DescargasRealizadas")
                        .HasColumnType("int");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiraEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EventoId");

                    b.HasIndex("FotoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Descargas", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualizadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ClientePrincipalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("FechaEventoUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.HasKey("Id");

                    b.HasIndex("ClientePrincipalId");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Eventos", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.EventoFavorito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("UsuarioId", "EventoId")
                        .IsUnique();

                    b.ToTable("EventosFavoritos", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Foto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("MarcaAguaStorageKey")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PreviewUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<DateTime>("SubidaEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventoId", "StorageKey")
                        .IsUnique();

                    b.ToTable("Fotos", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.FotoFavorita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FotoId");

                    b.HasIndex("UsuarioId", "FotoId")
                        .IsUnique();

                    b.ToTable("FotosFavoritas", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualizadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("MercadoPagoPaymentId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("MercadoPagoPreferenceId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PagadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualizadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MercadoPagoPreferenceId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EventoId");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.PedidoFoto", b =>
                {
                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PedidoId", "FotoId");

                    b.HasIndex("FotoId");

                    b.ToTable("PedidoFotos", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ActualizadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorreoPublico")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Instagram")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("Fotografia.Domain.Entities.Cliente", "UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.ComentarioEvento", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Evento", "Evento")
                        .WithMany("Comentarios")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fotografia.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ComentariosEventos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.ComentarioFoto", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Foto", "Foto")
                        .WithMany("Comentarios")
                        .HasForeignKey("FotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fotografia.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ComentariosFotos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Foto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Descarga", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Descargas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fotografia.Domain.Entities.Evento", "Evento")
                        .WithMany("Descargas")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fotografia.Domain.Entities.Foto", "Foto")
                        .WithMany()
                        .HasForeignKey("FotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fotografia.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Descargas")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Evento");

                    b.Navigation("Foto");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Evento", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Cliente", "ClientePrincipal")
                        .WithMany("EventosPrincipales")
                        .HasForeignKey("ClientePrincipalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fotografia.Domain.Entities.Usuario", "CreadoPorUsuario")
                        .WithMany("EventosCreados")
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClientePrincipal");

                    b.Navigation("CreadoPorUsuario");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.EventoFavorito", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Evento", "Evento")
                        .WithMany("Favoritos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fotografia.Domain.Entities.Usuario", "Usuario")
                        .WithMany("EventosFavoritos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Foto", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Evento", "Evento")
                        .WithMany("Fotos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.FotoFavorita", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Foto", "Foto")
                        .WithMany("Favoritos")
                        .HasForeignKey("FotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fotografia.Domain.Entities.Usuario", "Usuario")
                        .WithMany("FotosFavoritas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Foto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Pago", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Pedido", "Pedido")
                        .WithOne("Pago")
                        .HasForeignKey("Fotografia.Domain.Entities.Pago", "PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fotografia.Domain.Entities.Evento", "Evento")
                        .WithMany("Pedidos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.PedidoFoto", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Foto", "Foto")
                        .WithMany("PedidoFotos")
                        .HasForeignKey("FotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fotografia.Domain.Entities.Pedido", "Pedido")
                        .WithMany("PedidoFotos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Foto");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Descargas");

                    b.Navigation("EventosPrincipales");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Evento", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Descargas");

                    b.Navigation("Favoritos");

                    b.Navigation("Fotos");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Foto", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Favoritos");

                    b.Navigation("PedidoFotos");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Descargas");

                    b.Navigation("Pago");

                    b.Navigation("PedidoFotos");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Cliente");

                    b.Navigation("ComentariosEventos");

                    b.Navigation("ComentariosFotos");

                    b.Navigation("EventosCreados");

                    b.Navigation("EventosFavoritos");

                    b.Navigation("FotosFavoritas");
                });
#pragma warning restore 612, 618
        }
    }
}
