// <auto-generated />
using System;
using Fotografia.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fotografia.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601214849_AddOperationalManagementPhase3")]
    partial class AddOperationalManagementPhase3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fotografia.Domain.Entities.AgendaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("Programado");

                    b.Property<Guid?>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFinUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicioUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SesionPrivadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SolicitudPresupuestoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("Otro");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EventoId");

                    b.HasIndex("SesionPrivadaId");

                    b.HasIndex("SolicitudPresupuestoId");

                    b.HasIndex("Activo", "Estado");

                    b.HasIndex("FechaInicioUtc", "FechaFinUtc");

                    b.ToTable("AgendaItems", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.CarritoCompra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Estado")
                        .IsUnique()
                        .HasFilter("[Estado] = 'Activo'");

                    b.ToTable("CarritosCompra", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.CarritoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<Guid>("CarritoCompraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FotoPrivadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PaqueteEventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoItem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CarritoCompraId");

                    b.HasIndex("FotoId");

                    b.HasIndex("FotoPrivadaId");

                    b.HasIndex("PaqueteEventoId");

                    b.HasIndex("CarritoCompraId", "TipoItem", "FotoId")
                        .IsUnique()
                        .HasFilter("[FotoId] IS NOT NULL");

                    b.HasIndex("CarritoCompraId", "TipoItem", "FotoPrivadaId")
                        .IsUnique()
                        .HasFilter("[FotoPrivadaId] IS NOT NULL");

                    b.HasIndex("CarritoCompraId", "TipoItem", "PaqueteEventoId")
                        .IsUnique()
                        .HasFilter("[PaqueteEventoId] IS NOT NULL");

                    b.ToTable("CarritoItems", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualizadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documento")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasFilter("[UsuarioId] IS NOT NULL");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.ComentarioEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ComentariosEventos", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.ComentarioFoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FotoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ComentariosFotos", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Descarga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DescargasRealizadas")
                        .HasColumnType("int");

                    b.Property<Guid?>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiraEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FotoPrivadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("MaxDescargas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<DateTime?>("UltimaDescargaUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EventoId");

                    b.HasIndex("FotoId");

                    b.HasIndex("FotoPrivadaId");

                    b.HasIndex("PedidoId");

                    b.ToTable("Descargas", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ActualizadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ClientePrincipalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("Publicado");

                    b.Property<DateTime>("FechaEventoUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLimiteCompraUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<Guid?>("PortadaFotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("Visibilidad")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("Publico");

                    b.HasKey("Id");

                    b.HasIndex("ClientePrincipalId");

                    b.HasIndex("CreadoPorUsuarioId");

                    b.HasIndex("PortadaFotoId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Activo", "Estado", "Visibilidad");

                    b.ToTable("Eventos", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.EventoFavorito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.HasIndex("UsuarioId", "EventoId")
                        .IsUnique();

                    b.ToTable("EventosFavoritos", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Foto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("MarcaAguaStorageKey")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PreviewUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Procesada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<DateTime>("SubidaEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TieneMarcaAgua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventoId", "StorageKey")
                        .IsUnique();

                    b.ToTable("Fotos", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.FotoFavorita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FotoId");

                    b.HasIndex("UsuarioId", "FotoId")
                        .IsUnique();

                    b.ToTable("FotosFavoritas", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.FotoPrivada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("MarcaAguaStorageKey")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PreviewUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("SesionPrivadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("SesionPrivadaId");

                    b.HasIndex("SesionPrivadaId", "StorageKey")
                        .IsUnique();

                    b.ToTable("FotosPrivadas", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.NotaInterna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("EntidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntidadTipo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Activa", "FechaCreacionUtc");

                    b.HasIndex("EntidadTipo", "EntidadId");

                    b.ToTable("NotasInternas", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualizadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("MercadoPagoPaymentId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("MercadoPagoPreferenceId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PagadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.PaqueteEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IncluyeTodasLasFotos")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("PaquetesEvento", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualizadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("EventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MercadoPagoPreferenceId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EventoId");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.PedidoEstadoHistorial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("FechaCambioUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("PedidoId", "FechaCambioUtc");

                    b.ToTable("PedidoEstadoHistorial", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.PedidoFoto", b =>
                {
                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PedidoId", "FotoId");

                    b.HasIndex("FotoId");

                    b.ToTable("PedidoFotos", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.PedidoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FotoPrivadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PaqueteEventoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoItem")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("FotoId");

                    b.HasIndex("FotoPrivadaId");

                    b.HasIndex("PaqueteEventoId");

                    b.HasIndex("PedidoId");

                    b.ToTable("PedidoItems", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.PerfilFotografa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("BannerUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Biografia")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("CorreoPublico")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Facebook")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoPerfilUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Instagram")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Pais")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SitioWeb")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TextoBienvenida")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TikTok")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Titulo")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Activa")
                        .IsUnique()
                        .HasFilter("[Activa] = 1");

                    b.ToTable("PerfilesFotografa", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.PortfolioItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Categoria")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Destacado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("Activo", "Orden");

                    b.ToTable("PortfolioItems", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.PreguntaFrecuente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Categoria")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Activa", "Orden");

                    b.ToTable("PreguntasFrecuentes", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.ServicioFotografia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("CantidadFotosIncluidas")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1200)
                        .HasColumnType("nvarchar(1200)");

                    b.Property<string>("DuracionEstimada")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioDesde")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Activo", "Orden");

                    b.ToTable("ServiciosFotografia", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.SesionPrivada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSesionUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PrecioPaquete")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("SesionesPrivadas", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.SolicitudPresupuesto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("CantidadInvitados")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("Nuevo");

                    b.Property<DateTime?>("FechaActualizacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacionUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaTentativaUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lugar")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<Guid?>("ServicioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoEvento")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ServicioId");

                    b.HasIndex("Activa", "FechaCreacionUtc");

                    b.HasIndex("Estado", "FechaCreacionUtc");

                    b.ToTable("SolicitudesPresupuesto", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ActualizadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorreoPublico")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime>("CreadoEnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Instagram")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.AgendaItem", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fotografia.Domain.Entities.Evento", "Evento")
                        .WithMany()
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fotografia.Domain.Entities.SesionPrivada", "SesionPrivada")
                        .WithMany()
                        .HasForeignKey("SesionPrivadaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fotografia.Domain.Entities.SolicitudPresupuesto", "SolicitudPresupuesto")
                        .WithMany()
                        .HasForeignKey("SolicitudPresupuestoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Evento");

                    b.Navigation("SesionPrivada");

                    b.Navigation("SolicitudPresupuesto");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.CarritoCompra", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Usuario", "Usuario")
                        .WithMany("CarritosCompra")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.CarritoItem", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.CarritoCompra", "CarritoCompra")
                        .WithMany("Items")
                        .HasForeignKey("CarritoCompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fotografia.Domain.Entities.Foto", "Foto")
                        .WithMany("CarritoItems")
                        .HasForeignKey("FotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fotografia.Domain.Entities.FotoPrivada", "FotoPrivada")
                        .WithMany("CarritoItems")
                        .HasForeignKey("FotoPrivadaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fotografia.Domain.Entities.PaqueteEvento", "PaqueteEvento")
                        .WithMany("CarritoItems")
                        .HasForeignKey("PaqueteEventoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CarritoCompra");

                    b.Navigation("Foto");

                    b.Navigation("FotoPrivada");

                    b.Navigation("PaqueteEvento");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Cliente")
                        .HasForeignKey("Fotografia.Domain.Entities.Cliente", "UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.ComentarioEvento", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Evento", "Evento")
                        .WithMany("Comentarios")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fotografia.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ComentariosEventos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.ComentarioFoto", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Foto", "Foto")
                        .WithMany("Comentarios")
                        .HasForeignKey("FotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fotografia.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ComentariosFotos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Foto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Descarga", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Descargas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fotografia.Domain.Entities.Evento", "Evento")
                        .WithMany("Descargas")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fotografia.Domain.Entities.Foto", "Foto")
                        .WithMany()
                        .HasForeignKey("FotoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fotografia.Domain.Entities.FotoPrivada", "FotoPrivada")
                        .WithMany()
                        .HasForeignKey("FotoPrivadaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fotografia.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Descargas")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Evento");

                    b.Navigation("Foto");

                    b.Navigation("FotoPrivada");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Evento", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Cliente", "ClientePrincipal")
                        .WithMany("EventosPrincipales")
                        .HasForeignKey("ClientePrincipalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fotografia.Domain.Entities.Usuario", "CreadoPorUsuario")
                        .WithMany("EventosCreados")
                        .HasForeignKey("CreadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fotografia.Domain.Entities.Foto", "PortadaFoto")
                        .WithMany()
                        .HasForeignKey("PortadaFotoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClientePrincipal");

                    b.Navigation("CreadoPorUsuario");

                    b.Navigation("PortadaFoto");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.EventoFavorito", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Evento", "Evento")
                        .WithMany("Favoritos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fotografia.Domain.Entities.Usuario", "Usuario")
                        .WithMany("EventosFavoritos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Foto", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Evento", "Evento")
                        .WithMany("Fotos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.FotoFavorita", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Foto", "Foto")
                        .WithMany("Favoritos")
                        .HasForeignKey("FotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fotografia.Domain.Entities.Usuario", "Usuario")
                        .WithMany("FotosFavoritas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Foto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.FotoPrivada", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Cliente", "Cliente")
                        .WithMany("FotosPrivadas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fotografia.Domain.Entities.SesionPrivada", "SesionPrivada")
                        .WithMany("Fotos")
                        .HasForeignKey("SesionPrivadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("SesionPrivada");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.NotaInterna", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Pago", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Pedido", "Pedido")
                        .WithOne("Pago")
                        .HasForeignKey("Fotografia.Domain.Entities.Pago", "PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.PaqueteEvento", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Evento", "Evento")
                        .WithMany("Paquetes")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fotografia.Domain.Entities.Evento", "Evento")
                        .WithMany("Pedidos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.PedidoEstadoHistorial", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Pedido", "Pedido")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fotografia.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pedido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.PedidoFoto", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Foto", "Foto")
                        .WithMany("PedidoFotos")
                        .HasForeignKey("FotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fotografia.Domain.Entities.Pedido", "Pedido")
                        .WithMany("PedidoFotos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Foto");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.PedidoItem", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Foto", "Foto")
                        .WithMany("PedidoItems")
                        .HasForeignKey("FotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fotografia.Domain.Entities.FotoPrivada", "FotoPrivada")
                        .WithMany("PedidoItems")
                        .HasForeignKey("FotoPrivadaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fotografia.Domain.Entities.PaqueteEvento", "PaqueteEvento")
                        .WithMany("PedidoItems")
                        .HasForeignKey("PaqueteEventoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Fotografia.Domain.Entities.Pedido", "Pedido")
                        .WithMany("PedidoItems")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Foto");

                    b.Navigation("FotoPrivada");

                    b.Navigation("PaqueteEvento");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.SesionPrivada", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.Cliente", "Cliente")
                        .WithMany("SesionesPrivadas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.SolicitudPresupuesto", b =>
                {
                    b.HasOne("Fotografia.Domain.Entities.ServicioFotografia", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.CarritoCompra", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Descargas");

                    b.Navigation("EventosPrincipales");

                    b.Navigation("FotosPrivadas");

                    b.Navigation("Pedidos");

                    b.Navigation("SesionesPrivadas");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Evento", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Descargas");

                    b.Navigation("Favoritos");

                    b.Navigation("Fotos");

                    b.Navigation("Paquetes");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Foto", b =>
                {
                    b.Navigation("CarritoItems");

                    b.Navigation("Comentarios");

                    b.Navigation("Favoritos");

                    b.Navigation("PedidoFotos");

                    b.Navigation("PedidoItems");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.FotoPrivada", b =>
                {
                    b.Navigation("CarritoItems");

                    b.Navigation("PedidoItems");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.PaqueteEvento", b =>
                {
                    b.Navigation("CarritoItems");

                    b.Navigation("PedidoItems");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Descargas");

                    b.Navigation("HistorialEstados");

                    b.Navigation("Pago");

                    b.Navigation("PedidoFotos");

                    b.Navigation("PedidoItems");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.SesionPrivada", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("Fotografia.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("CarritosCompra");

                    b.Navigation("Cliente");

                    b.Navigation("ComentariosEventos");

                    b.Navigation("ComentariosFotos");

                    b.Navigation("EventosCreados");

                    b.Navigation("EventosFavoritos");

                    b.Navigation("FotosFavoritas");
                });
#pragma warning restore 612, 618
        }
    }
}
